[app:main]
use: call:h.subtask:create_app

# Elasticsearch configuration. The WebSocket does not actually use ES but
# it does use the same config loading code which checks for these settings.
es.url: http://localhost:9200

secret_key: notverysecretafterall

# SQLAlchemy configuration -- See SQLAlchemy documentation
sqlalchemy.url: postgresql://postgres@localhost/postgres

# secret_key configuration. h_api_auth_cookie_secret_key and
# h_api_auth_cookie_salt are for api_authcookie
h_api_auth_cookie_secret_key: dev_h_api_auth_cookie_secret_key

broker_url: amqp://guest:guest@10.89.3.23:5672//

kn.repository: ./KMASS_2025_data/DSwAPL_2025/AoS-json ./KMASS_2025_data/DSwAPL_2025/CourseHB-json ./KMASS_2025_data/DSwAPL_2025/EDiQ-json ./KMASS_2025_data/DSwAPL_2025/UnitHB-json ./KMASS_2025_data/DSwAPL_2025/learnHQ-json ./KMASS_2025_data/DSwAPL_2025/teachHQ-json ./KMASS_2025_data/DSwAPL_2025/PolicyBank-pdf ./KMASS_2025_data/DSwAPL_2025/CourseMap-pdf
kn.database: ./background_knowledge_1205.faiss
kn.model_name: llama3.1

[loggers]
keys = root, gunicorn.error, h

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console

[logger_gunicorn.error]
level = INFO
handlers =
qualname = gunicorn.error

[logger_h]
level = INFO
handlers =
qualname = h

[handler_console]
level = NOTSET
class = StreamHandler
args = ()
formatter = generic

[formatter_generic]
format = %(asctime)s [%(process)d] [%(name)s:%(levelname)s] %(message)s
